version: "3.9"

services:
  web:
    build: .
    container_name: octoflow_web
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: octoflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: octoflow
      POSTGRES_USER: octoflow
      POSTGRES_PASSWORD: octoflow
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: octoflow_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: